twig:
    paths:
       'altermeso/templates': ~
       'templates': ~
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
       infos: '@App\GramcServices\ServiceInfos'
       serviceVersions: '@App\GramcServices\ServiceVersions'
       serviceProjets: '@App\GramcServices\ServiceProjets'
       mailadmin: '%mailadmin%'
       mailsupport: '%mailsupport%'
       mesoc: '%mesoc%'
       mesoc_web: '%mesoc_web%'
       mesoc_attrib: '%mesoc_attrib%'
       mesoc_merci: '%mesoc_merci%'
       mesoc_cgu: '%mesoc_cgu%'
       mesoc_visu: '%mesoc_visu%'
       mesoc_formation: '%mesoc_formation%'
       mesoc_address: '%mesoc_address%'
       conso_seuil_1: '%conso_seuil_1%'
       conso_seuil_2: '%conso_seuil_2%'
       noconso: '%noconso%'
       norattachement: '%norattachement%'
       nodata: '%nodata%'
       noedition_expertise: '%noedition_expertise%'
       heures_ete: '%heures_ete%'
       prj_prefix: '%prj_prefix%'
       prj_seuil_sess: '%prj_seuil_sess%'
       max_expertises_nb: '%max_expertises_nb%'
       ressources_conso_group: '%ressources_conso_group%'
       ressources_conso_user: '%ressources_conso_user%'
       max_page_nb: '%max_page_nb%'
       max_size_doc: '%max_size_doc%'
       rapport_dactivite: '%rapport_dactivite%'
       fichier_attache: '%fichier_attache%'
       coll_login: '%coll_login%'
       noinvitation: '%noinvitation%'
       resp_peut_modif_collabs: '%resp_peut_modif_collabs%'
       
